# #############################
# # BUILD FOR LOCAL DEVELOPMENT
# #############################

FROM oven/bun AS development

WORKDIR /app

RUN apt-get update -y && apt-get install -y openssl

COPY package*.json bun.lock ./

COPY prisma ./prisma/

RUN bun install

COPY . .

EXPOSE 3333

CMD [ "bun", "dev" ]
