# #############################
# # BUILD FOR LOCAL DEVELOPMENT
# #############################

FROM oven/bun AS development

WORKDIR /app/frontend

COPY apps/frontend/package*.json ./

RUN bun install

COPY apps/frontend/. ./

COPY tsconfig.json ../tsconfig.json

EXPOSE 3000

CMD [ "bun", "dev" ]
