# #############################
# # BUILD FOR LOCAL DEVELOPMENT
# #############################

FROM oven/bun AS development

WORKDIR /app

COPY package*.json ./

RUN bun install

COPY . .

EXPOSE 3000

CMD [ "bun", "dev" ]
