# #############################
# # BUILD FOR LOCAL DEVELOPMENT
# #############################

FROM oven/bun AS development

WORKDIR /app/backend

RUN apt-get update -y && apt-get install -y openssl

COPY apps/backend/package*.json ./

COPY apps/backend/prisma ./prisma/

RUN bun install

RUN bun install @prisma/client

RUN bunx prisma generate

COPY apps/backend/. ./

COPY tsconfig.json ../tsconfig.json

EXPOSE 3333

CMD [ "bun", "dev" ]
