# #############################
# # BUILD FOR LOCAL DEVELOPMENT
# #############################

FROM oven/bun AS development

WORKDIR /app

RUN apt-get update -y && apt-get install -y openssl

COPY package*.json ./

COPY prisma ./prisma/

RUN bun install

RUN bun install @prisma/client

RUN bunx prisma generate

COPY . .

EXPOSE 3333

CMD [ "bun", "dev" ]
