export const ERROR_CODES = {
    ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
    ACCOUNT_INVALID: 'ACCOUNT_INVALID',
    FORBIDDEN: 'FORBIDDEN',
    INVALID_PASSWORD: 'INVALID_PASSWORD',
    TOKEN_MISSING: 'TOKEN_MISSING',
    TOKEN_INVALID: 'TOKEN_INVALID',
    EMAIL_EXISTS: 'EMAIL_EXISTS',
} as const

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES]
