export const ERROR_CODES = {
    ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
    ACCOUNT_INVALID: 'ACCOUNT_INVALID',
    FORBIDDEN: 'FORBIDDEN',
    INVALID_PASSWORD: 'INVALID_PASSWORD',
    TOKEN_MISSING: 'TOKEN_MISSING',
    TOKEN_INVALID: 'TOKEN_INVALID',
    EMAIL_EXISTS: 'EMAIL_EXISTS',
    UNAUTHORIZED: 'UNAUTHORIZED',
    BOARD_NAME_DUPLICATED: 'BOARD_NAME_DUPLICATED',
    NOT_FOUND: 'NOT_FOUND',
    BOARD_NOT_FOUND: 'BOARD_NOT_FOUND',
    ALREADY_MEMBER: 'ALREADY_MEMBER',
    CANNOT_REMOVE_OWNER: 'CANNOT_REMOVE_OWNER',
    CANNOT_SELF_REMOVE: 'CANNOT_SELF_REMOVE',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    CANNOT_CHANGE_OWNER_ROLE: 'CANNOT_CHANGE_OWNER_ROLE',
    CANNOT_SELF_CHANGE_ROLE: 'CANNOT_SELF_CHANGE_ROLE',
    TRANSFER_OWNER_NOT_ALLOWED: 'TRANSFER_OWNER_NOT_ALLOWED',
    CANNOT_TRANSFER_TO_SELF: 'CANNOT_TRANSFER_TO_SELF',
    ALREADY_OWNER: 'ALREADY_OWNER',
    LIST_NOT_FOUND: 'LIST_NOT_FOUND',
    LIST_ALREADY_ARCHIVED: 'LIST_ALREADY_ARCHIVED',
    LIST_NOT_BELONG_TO_BOARD: 'LIST_NOT_BELONG_TO_BOARD',
    LIST_NOT_ARCHIVED: 'LIST_NOT_ARCHIVED',
    BOARD_ARCHIVED: 'BOARD_ARCHIVED',
    PERMISSION_DENIED: 'PERMISSION_DENIED',
    AUTH: {
        ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
        ACCOUNT_INVALID: 'ACCOUNT_INVALID',
        INVALID_PASSWORD: 'INVALID_PASSWORD',
        EMAIL_EXISTS: 'EMAIL_EXISTS',
        ACCOUNT_EXISTS: 'ACCOUNT_EXISTS',
        TOKEN_MISSING: 'TOKEN_MISSING',
        TOKEN_INVALID: 'TOKEN_INVALID',
        UNAUTHORIZED: 'UNAUTHORIZED',
        EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
        TOKEN_ALREADY_USED: 'TOKEN_ALREADY_USED',
        TOKEN_EXPIRED: 'TOKEN_EXPIRED',
        ALREADY_VERIFIED: 'ALREADY_VERIFIED'
    },
    USER: {
        NOT_FOUND: 'USER_NOT_FOUND',
        ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
        ALREADY_OWNER: 'ALREADY_OWNER',
        CANNOT_REMOVE_OWNER: 'CANNOT_REMOVE_OWNER',
        CANNOT_SELF_REMOVE: 'CANNOT_SELF_REMOVE',
        CANNOT_CHANGE_OWNER_ROLE: 'CANNOT_CHANGE_OWNER_ROLE',
        CANNOT_SELF_CHANGE_ROLE: 'CANNOT_SELF_CHANGE_ROLE',
        TRANSFER_OWNER_NOT_ALLOWED: 'TRANSFER_OWNER_NOT_ALLOWED',
        CANNOT_TRANSFER_TO_SELF: 'CANNOT_TRANSFER_TO_SELF',
        LIST_NOT_FOUND: 'LIST_NOT_FOUND'
    },
    WORKSPACE: {
        ROLE_INVALID: 'WORKSPACE_ROLE_INVALID',
        NAME_INVALID: 'WORKSPACE_NAME_INVALID',
        NAME_DUPLICATE: 'WORKSPACE_NAME_DUPLICATE',
        NOT_FOUND: 'WORKSPACE_NOT_FOUND',
        FORBIDDEN: 'WORKSPACE_FORBIDDEN',
        INTERNAL_ERROR: 'WORKSPACE_INTERNAL_ERROR',
        USER_NOT_FOUND: 'WORKSPACE_USER_NOT_FOUND',
        MEMBER_EXISTS: 'WORKSPACE_MEMBER_EXISTS',
        REMOVE_OWNER_DENIED: 'WORKSPACE_REMOVE_OWNER_DENIED',
        TRANSFER_TO_SELF: 'WORKSPACE_TRANSFER_TO_SELF',
        LEAVE_OWNER_DENIED: 'WORKSPACE_LEAVE_OWNER_DENIED'
    },
    BOARD: {
        NAME_EXISTS: 'BOARD_NAME_EXISTS',
        FORBIDDEN: 'BOARD_FORBIDDEN',
        NOT_FOUND: 'BOARD_NOT_FOUND',
        ALREADY_ARCHIVED: 'BOARD_ALREADY_ARCHIVED',
        NOT_ARCHIVED: 'BOARD_NOT_ARCHIVED',
        USER_ALREADY_MEMBER: 'BOARD_USER_ALREADY_MEMBER',
        REMOVE_OWNER_NOT_ALLOWED: 'BOARD_REMOVE_OWNER_NOT_ALLOWED',
        USER_NOT_BOARD_MEMBER: 'BOARD_USER_NOT_BOARD_MEMBER',
        ALREADY_FAVORITE: 'BOARD_ALREADY_FAVORITE'
    },
    LIST: {
        NAME_EXISTS: 'LIST_NAME_EXISTS',
        NOT_FOUND: 'LIST_NOT_FOUND',
        ALREADY_ARCHIVED: 'LIST_ALREADY_ARCHIVED',
        NOT_ARCHIVED: 'LIST_NOT_ARCHIVED',
        ARCHIVED: 'LIST_ARCHIVED',
        INVALID: 'LIST_INVALID',
        INVALID_ORDER: 'LIST_INVALID_ORDER',
        ALREADY_IN_BOARD: 'LIST_ALREADY_IN_BOARD',
        MOVE_FAILED: 'LIST_MOVE_FAILED',
        INVALID_MOVE: 'LIST_INVALID_MOVE'
    },
    CARD: {
        NOT_FOUND: 'CARD_NOT_FOUND',
        ARCHIVED: 'CARD_ARCHIVED',
        ALREADY_ARCHIVED: 'CARD_ALREADY_ARCHIVED',
        INVALID_ORDER: 'CARD_INVALID_ORDER',
        NOT_ARCHIVED: 'CARD_NOT_ARCHIVED',
        CHECKLIST_NOT_FOUND: 'CARD_CHECKLIST_NOT_FOUND',
        CHECKLIST_MISMATCH: 'CARD_CHECKLIST_MISMATCH',
        CHECKLIST_ITEM_NOT_FOUND: 'CARD_CHECKLIST_ITEM_NOT_FOUND',
        CHECKLIST_ITEM_MISMATCH: 'CARD_CHECKLIST_ITEM_MISMATCH'
    },
    BOARD_CUSTOM_FIELD: {
        NOT_FOUND: 'BOARD_CUSTOM_FIELD_NOT_FOUND',
        INVALID_BOARD: 'BOARD_CUSTOM_FIELD_INVALID_BOARD'
    },
    GENERAL: {
        FORBIDDEN: 'FORBIDDEN'
    },
    SYSTEM: {
        MAIL_FAILED: 'SYSTEM_MAIL_FAILED'
    }
} as const

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES]
