export const ERROR_CODES = {
    ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
    ACCOUNT_INVALID: 'ACCOUNT_INVALID',
    FORBIDDEN: 'FORBIDDEN',
    INVALID_PASSWORD: 'INVALID_PASSWORD',
    TOKEN_MISSING: 'TOKEN_MISSING',
    TOKEN_INVALID: 'TOKEN_INVALID',
    EMAIL_EXISTS: 'EMAIL_EXISTS',
    UNAUTHORIZED: 'UNAUTHORIZED',
    BOARD_NAME_DUPLICATED: 'BOARD_NAME_DUPLICATED',
    NOT_FOUND: 'NOT_FOUND',
    BOARD_NOT_FOUND: 'BOARD_NOT_FOUND',
    ALREADY_MEMBER: 'ALREADY_MEMBER',
    CANNOT_REMOVE_OWNER: 'CANNOT_REMOVE_OWNER',
    CANNOT_SELF_REMOVE: 'CANNOT_SELF_REMOVE',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    CANNOT_CHANGE_OWNER_ROLE: 'CANNOT_CHANGE_OWNER_ROLE',
    CANNOT_SELF_CHANGE_ROLE: 'CANNOT_SELF_CHANGE_ROLE',
    TRANSFER_OWNER_NOT_ALLOWED: 'TRANSFER_OWNER_NOT_ALLOWED',
    CANNOT_TRANSFER_TO_SELF: 'CANNOT_TRANSFER_TO_SELF',
    ALREADY_OWNER: 'ALREADY_OWNER'
} as const

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES]
